### ISSUE TITLE
Add meeting minutes to the wiki

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#11]
**Describe the task that needs to be done.**
We need our meeting minutes that are kept in the google drive to be shifted to the wiki 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Someone just needs to copy and add the correct markup 
**Notes**

**Comment by JafarMaash** [comment]
Added the backend meeting's minutes to the wiki (11/03/22)
