### ISSUE TITLE
Populate data in the memory database to be used for demo purposes

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#111]
**Describe the task that needs to be done.**
Create a SQL file that will populate the backend database with data that can be used for demonstration purposes

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Spring-boot automatically scans `/src/main/resources` for a `*.sql` file and runs the commands upon initialisation 

**Notes**

**Comment by scorpionknifes** [comment]
LGTM
