### ISSUE TITLE
Implement get ChatList endpoint 

### ISSUE THREAD

**Issue by scorpionknifes** [SE701-T1/backend#112]
**Describe the task that needs to be done.**

Need an endpoint from the backend to get the chat list, last message, and timestamp.

![image](https://user-images.githubusercontent.com/23299540/159107535-48a8effa-c02c-4496-b978-759306f91623.png)

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

Add a method to get lastmessage and return last message with timestamp.

Mock from frontend
```js
/**
 * Fetches data of the current users buddy chat list
 * @return {Promise} current users buddy chat list
 */
export const getBuddyChatList = async () => [
  {
    id: 1211,
    name: 'Sam',
    lastMessage: 'hey',
    timestamp: moment('2022-03-18T07:19:16.780Z').toDate(),
  },
  {
    id: 1212,
    name: 'Ben',
    lastMessage: 'hello',
    timestamp: moment('2022-03-18T07:19:16.780Z').toDate(),
  },
  {
    id: 1213,
    name: 'Tom',
    lastMessage: 'whats up',
    timestamp: moment('2022-03-18T07:19:16.780Z').toDate(),
  },
];
```

**Notes**

**Comment by ff-dev-45** [comment]
LGTM
