### ISSUE TITLE
Fixing endpoint types and updating UserDTO to have buddyCount

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#119]
**Describe the task that needs to be done.**
Fixing the endpoints in pairingController to have the correct return type for swagger documentation, also updating the endpoints that return UserDTO to have the getBuddyCount call done

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Adding in the correct type to the ResponseEntity so that swagger can display the correct info
Add in 2 lines to where UserDTO's are returned with the command to get and set the buddyCount
**Notes**

**Comment by scorpionknifes** [comment]
LGTM
