### ISSUE TITLE
Update Wiki for Communication

### ISSUE THREAD

**Issue by dogeliness** [SE701-T1/backend#122]
**Describe the task that needs to be done.**
Add documentation for the Wiki on the communication endpoint

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Add to future tasks, structure pages or create a new one

**Notes**

**Comment by ejstuart** [comment]
Look's good! I'll work on this one.

**Comment by ejstuart** [comment]
I've updated the frontend repo's wiki with the relevant information.
