### ISSUE TITLE
Remove BasicEndpoints that were setup as a demonstration for backend

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#125]
**Describe the task that needs to be done.**
`BasicController`, `BasicService` etc were added as a means to test the server worked, but also show the basic structure and annotations required for the backend team. Now they are obsolete and affecting the file structure, so it would make sense to remove them

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
remove the related files
**Notes**

**Comment by scorpionknifes** [comment]
LGTM
