### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by R055A** [SE701-T1/backend#160]
**Describe the task that needs to be done.**
*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*

Update the Backend and Frontend Wiki to reflect changes made to the Backend repository during the second assignment to bring it up-to-date for any future contributing.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

Review the current state of the repository, and make changes where necessary to bring the Backend and Frontend Wiki up-to-date with changes made to the Backend repository.

**Notes**

**Comment by R055A** [comment]
I will edit pages:
* ~~Backend Endpoints (for my own contributions)~~
* ~~Backend Entity Design~~
* ~~DevOps~~
* ~~Contributing Log (for my own contributions)~~
* ~~Contributors~~
* ~~Future Works (update Backend future work, add code coverage improvement task for Frontend future work)~~
* ~~Meeting Minutes~~

**Comment by hiin3d55** [comment]
I will edit pages:
- ~~Backend Endpoints~~
- ~~Contributors~~
- ~~Contributing Log~~
- ~~Meeting Minutes~~

**Comment by kimslor** [comment]
I will edit pages:

- ~~Backend Endpoints (for my own contributions)~~
- ~~Contributors~~
- ~~Contributing Log~~
