### ISSUE TITLE
Timetable File Processing

### ISSUE THREAD

**Issue by jessicafenwick** [SE701-T1/backend#21]
**Describe the task that needs to be done.**
Work out how to take in timetable file (only .ics)  and process it to get specific courses (and any other information).
Need to look into the file format and options for upload. 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
.ics file can be read and relevant information stored in database seperately

**Notes**
Dependent on database solution being decided and framework implemented - #13

**Comment by ff-dev-45** [comment]
Any update on this issue, since issue 13 was resolved with us moving ahead with H2 for now

**Comment by dlee432** [comment]
Been working on this issue, using an external library (iCal4j) to parse .ics file and get the courses from them.
