### ISSUE TITLE
User backend setup 

### ISSUE THREAD

**Issue by JafarMaash** [SE701-T1/backend#23]
**Describe the task that needs to be done.**
Setup User entity, DTO, repository, service and controller. 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
User entity fields:
- id: UUID 
- name: string 
- email: string 
- pair: Pair
- authCookie: String/Cookie

Endpoints: 

Retrieving users
GET /users/{id}
Response:
200 OK w/ User Entity

**Notes**

**Comment by ff-dev-45** [comment]
What is the pair field representing?

**Comment by uoa-ypec413** [comment]
> What is the pair field representing?

The pair field will be a `Pair` entity which has 2 `User` instances. 

We were thinking of having a `User` have a `buddy` field which would also be a `User` instance, but decided to avoid a self-referencing relationship.

Let me know if there's another way you'd prefer to store paired users :)

**Comment by ff-dev-45** [comment]
Okay that makes sense, I believe earlier on in the original project idea description, there was the concept of if users wanted to opt in for pairing, or if they would prefer to not. 

Is this still a concept that is being considered for users?

**Comment by uoa-ypec413** [comment]
> Okay that makes sense, I believe earlier on in the original project idea description, there was the concept of if users wanted to opt in for pairing, or if they would prefer to not.
> 
> Is this still a concept that is being considered for users?

We discussed having a `pairingActivated` boolean field in the User Entity, but decided against adding that for the initial setup issue as we haven't discussed with pairing team yet, and thought we could add it in later issues (same with the timetable).

 If your team is happy with a `pairingActivated` field, I'm happy to add it to this issue though!

**Comment by ff-dev-45** [comment]
I understand that reasoning completely, when you have time if you can create an issue, I think someone from my team would definitely be willing to take on the task of adding it, after the initial setup is all done if that is fine with you (otherwise happy to leave it with your team still as well!)
