### ISSUE TITLE
Document pairing algorithm processes

### ISSUE THREAD

**Issue by rayaway2020** [SE701-T1/backend#24]
**Describe the task that needs to be done.**
Documentation about the pairing algorithm including how the pairing starts, how the pairing works and all the paths users can go(choose one specific paper/multiple ones, actions like send/refuse request?) to give both the front-end design and back-end messaging team more clear identifications.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
A wiki file in repo to record all the decisions and ideas have been brought up.

**Notes**

**Comment by ff-dev-45** [comment]
LGTM

**Comment by ff-dev-45** [comment]
Wiki page will be added to the front-end wiki, as we are putting all our wiki pages in one place on one repo (front-end repo already has the wiki started).

In the future we may copy relevant pages back to backend, but this is low priority

**Comment by ff-dev-45** [comment]
@rayaway2020 checking if you managed to get this done, and if so close the issue!
