### ISSUE TITLE
Backend Wiki to point to front-end wiki

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#25]
**Describe the task that needs to be done.**
A wiki page needs to be created for the backend, explaining and linking towards the front-end repo wiki.
We are doing this to consolidate all our wiki documents in one place (one repo) rather than duplicating and doubling the work for any new wiki additions. 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
A wiki page added to the backend
**Notes**

**Comment by JafarMaash** [comment]
Added link to front end wiki in backend wiki
