### ISSUE TITLE
Create endpoint for Adding Buddy

### ISSUE THREAD

**Issue by shreyasingaraju** [SE701-T1/backend#28]
**Describe the task that needs to be done.**
Set up endpoint and documentation for adding a buddy by communicating with 'Users'. 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Set up empty endpoint methods with descriptions for adding a buddy that will show up on swagger. 

Endpoint: addBuddy
Path: /api/pairing/
Request: Current User ID and added buddy's User ID. 
Operation: PUT
Response: 200 OK. Adds new buddy's User ID to current user's array of all buddies.

**Notes**

**Comment by ff-dev-45** [comment]
Would you be able to include examples of the endpoint details in the solution description?

For example,

Endpoint: addBuddy
path: /api/pairing/
Request: Contains array of course Id's
Response: 200 OK & array of students + their details

If you have any questions about what the endpoint should look like for now, don't hesitate to reach out here or on the discord :)

**Comment by ff-dev-45** [comment]
LGTM with the additions, assigned to self to get working on it!

**Comment by ff-dev-45** [comment]
This issue is blocking #47
