### ISSUE TITLE
Create endpoint for Matching a Buddy

### ISSUE THREAD

**Issue by shreyasingaraju** [SE701-T1/backend#30]
**Describe the task that needs to be done.**
Set up endpoint and documentation for matching a User with a buddy. 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Set up empty endpoint methods with descriptions for matching a buddy that will show up on swagger.

Endpoint: matchBuddy
Path: /api/pairing/
Request: Array of Course ID's and User ID's 
Operation: GET
Response: 200 OK. 

**Notes**

**Comment by ff-dev-45** [comment]
Similar comment for whats in issue #28 about endpoint example

**Comment by ff-dev-45** [comment]
LGTM with changes, assigned to self to start working on it

**Comment by ff-dev-45** [comment]
This issue is blocking #49
