### ISSUE TITLE
Implement login endpoint 

### ISSUE THREAD

**Issue by JafarMaash** [SE701-T1/backend#33]
**Describe the task that needs to be done.**
Implement the endpoint to log users in 

**Describe what a solution to your proposed task might look like (and any alternatives considered).**
When users sign in with Google in the frontend, the client is given an ID token which it can then pass to the backend. In the backend, we could take that token and verify it using Google's API. Once verified, there are two options:
- If the user/email doesn't exist in our database:
  - register them and maybe prompt to import timetable?
- If the user/email does exist in our database:
  - Create a session for them - see next line down
 
Once the token is verified, generate our own JWT to pass back to the front end when returning, containing the user ID
 
**Notes**
Aim to complete by Wednesday night :) (16/03)

Some links:
https://developers.google.com/identity/protocols/oauth2/web-server
https://developers.google.com/identity/gsi/web/guides/verify-google-id-token

**Comment by uoa-ypec413** [comment]
LGTM

**Comment by ff-dev-45** [comment]
Raised priority, 
I think revision is needed for more details about the solution, in regards to specifics around the solution:
- type of token used (jwt was mentioned in the discord, could this be clarified on this issue please)
- database changes, how does the database know the id/token and which table/schema is this in?

After those revisions, it will lgtm
