### ISSUE TITLE
Rename Pair entity to Buddies

### ISSUE THREAD

**Issue by uoa-ypec413** [SE701-T1/backend#35]
**Describe the task that needs to be done.**
The `Pair` entity currently has a list of `User` instances, this entity should be renamed to `Buddies` as a list implies there could be more than 2 users.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Rename `Pair` entity to `Buddies`
Update `pair` field in `User` entity to `buddies`

**Notes**

**Comment by ff-dev-45** [comment]
LGTM
