### ISSUE TITLE
Implement Timetable endpoint

### ISSUE THREAD

**Issue by ThomasHolsterUOA** [SE701-T1/backend#36]
**Describe the task that needs to be done.**
Set up a timetable endpoint with dummy data

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Create the necessary Spring classes to serve dummy data at /api/timetable with a user id as a parameter

**Notes**
The actual timetable structure hasn't been decided yet so the specific configuration is subject to change
Approved via discussion within timetabling team

**Comment by dlee432** [comment]
LGTM!
