### ISSUE TITLE
Implement Socket I/O Read Event

### ISSUE THREAD

**Issue by ejstuart** [SE701-T1/backend#41]
**Describe the task that needs to be done.**
*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*

Create and implement an event that flags a message as read by the user.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

Socket I/O event that updates history of messages with a flag that a message has been read.

**Notes**

As discussed in communications group meeting (see meeting minutes in wiki)

**Comment by dogeliness** [comment]
Very useful PR
