### ISSUE TITLE
Implement API Specification for Endpoints

### ISSUE THREAD

**Issue by uoa-ppat965** [SE701-T1/backend#42]
**Describe the task that needs to be done.**
Setting up to do the implemented endpoints (using swagger)

*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*
This will allow us to describe the entire API

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
The proposed solution is an API that we will be able to drive the development further.

**Notes**
Specification discussed in initial communication group meeting (see meeting minutes in wiki)

**Comment by ejstuart** [comment]
LGTM, matches up with what we discussed
