### ISSUE TITLE
Implement Endpoint Logic for Sending and Subcribing to Messages

### ISSUE THREAD

**Issue by dogeliness** [SE701-T1/backend#43]
**Describe the task that needs to be done.**
Implement the endpoint logic for communications/messages to retrieve message history

Describe how a solution to your proposed task might look like (and any alternatives considered).
Functional message sending + subscription 

**Notes**

**Comment by ejstuart** [comment]
LGTM, matches up with what we discussed in the meeting

**Comment by NicholasBatesNZ** [comment]
As discussed on Discord, this is no longer necessary as #72 includes SocketIO events which handle this functionality.
