### ISSUE TITLE
Implement Send/Receive Message Events

### ISSUE THREAD

**Issue by NicholasBatesNZ** [SE701-T1/backend#44]
**Describe the task that needs to be done.**
*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*

Implement Send/Receive message socket events. Depends on #38 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

SendMessage - sends message to a room (client -> server)
```
{
    sender_id: “the id of self”
    receiver_id: “the id of the user you sending to”
    message: “string”
    timestamp: “unix time”
}
```

ReceiveMessage - server sends client a message (server -> client)         
```
{
    sender_id: “the id of sender”
    receiver_id: “the id of the receiver”
    message: “string”
    timestamp: ”unix time”
}
```

**Notes**
As discussed in communications meeting 14/03/22 (see minutes in wiki)

**Comment by ejstuart** [comment]
LGTM, matches up with what we discussed, very detailed!

**Comment by NicholasBatesNZ** [comment]
Working on this now :+1:
