### ISSUE TITLE
Implement Socket I/O Online Event

### ISSUE THREAD

**Issue by ejstuart** [SE701-T1/backend#45]
**Describe the task that needs to be done.**
*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*

Create and implement an event that sends to a client whenever a new user joins the socket i/o.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

Wrap join event with a user id

**Notes**

As discussed in communications group meeting (see meeting minutes in wiki)

**Comment by uoa-ppat965** [comment]
Seems fine

**Comment by dogeliness** [comment]
This PR is excellent
