### ISSUE TITLE
Implement the logic for addBuddy endpoint

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#47]
**Describe the task that needs to be done.**
After the blank endpoint is created for the addBuddy endpoint in the Pairing service, the actual logic and implementation needs to be complete with appropriate testing

Depends on: #28 
Blocking: #50

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
The endpoint takes in a `AddBuddyDTO` which is a DTO to represent a JSON body that is passed in with the post request. This request contains a `userId` and `buddyId` 

The addBuddy endpoint needs to:
- (TBC with user team) Authorize that the user who is sending the request is the user
- Verify that the  `userId` and `buddyId` exist in the User table
- Check to make sure that the buddy is not already added to the user
- Make a change to both users (user & buddy) updating their buddy lists to contain each id
- (TBC with communication team) send out a chat message for both users with a welcome message (TBD, needs approval from the communication team)
- Corresponding response code is returned based on success/failure

Response codes:
201 Created, if new buddy record is created
404 Not Found, if either id does not exist
400 Bad request, if a buddy match already exists between users
(TBD) 403 not authorized, if the user authentication system is set up (added as a later issue)

**Notes**
- Authorization will be confirmed with user team, and added in a later issue
- Communication team will be consulted in regards to welcome message, added in a later issue

**Comment by scorpionknifes** [comment]
LGTM
