### ISSUE TITLE
Implement logic for removeBuddy Endpoint

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#48]
**Describe the task that needs to be done.**
After the blank endpoint is created for the removeBuddy endpoint in the Pairing service, the actual logic and implementation needs to be complete with appropriate testing

Depends on: #29 
Blocking: #50 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
The endpoint takes in a `buddyId` which is the id of the buddy to remove

The addBuddy endpoint needs to:
- (TBC with user team) Authorize that the user who is sending the request is the user
- Verify that the `buddyId` exist in the User table
- Check to make sure that the buddy is added to the user
- Make a change to both users (user & buddy) updating their buddy lists to not contain each id
- (TBC with communication team) send out a message to delete the archive (TBD, needs approval from the communication team)
- Corresponding response code is returned based on success/failure

Response codes:
200 Ok, if the operation was successful
404 Not Found, if buddy id does not exist
400 Bad request, if a buddy match does not exist between users
(TBD) 403 not authorized, if the user authentication system is set up (added as a later issue)

**Notes**
- Authorization will be confirmed with user team, and added in a later issue
- Communication team will be consulted in regards to welcome message, added in a later issue

**Comment by scorpionknifes** [comment]
LGTM
