### ISSUE TITLE
Implement the logic of the matchBuddy endpoint

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#49]
**Describe the task that needs to be done.**
After the blank endpoint is created for the matchBuddy endpoint in the Pairing service, the actual logic and implementation needs to be complete with appropriate testing

Depends on #30 #22 
Blocking: #50

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
The endpoint takes in a list of courses from a JSON body that is passed in with the post request. 

The matchBuddy endpoint needs to:
- (TBC with user team) Authorize that the user who is sending the request is the user
- Check that the courses passed in are all valid courses
- Query the database to get back all students who are in the courses, remove any duplicates, and students who don't want to be paired
- Get all relevant information of the students returned, and format them into a JSON list to be sent back to the frontend
- Corresponding response code is returned based on success/failure

Response codes:
200 Ok, with list of possible buddies
204 No Content, if no buddies found
404 Not Found, if courses passed in are not valid
(TBD) 403 not authorized, if the user authentication system is set up (added as a later issue)

**Notes**
- Authorization will be confirmed with user team, and added in a later issue
- Communication team will be consulted in regards to welcome message, added in a later issue

**Comment by ff-dev-45** [comment]
@scorpionknifes does this issue SGTY?

**Comment by scorpionknifes** [comment]
LGTM
