### ISSUE TITLE
Endpoint to store uploaded timetable file

### ISSUE THREAD

**Issue by jessicafenwick** [SE701-T1/backend#52]
**Describe the task that needs to be done.**
Create API endpoint that stores uploaded .ics file

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
API endpoint can take in a uploaded .ics file and stores that file in a temporary folder. 

**Notes**
Discussed in meeting on 14/03, is just for when a file is uploaded, not provided via URL

**Comment by dlee432** [comment]
LGTM!

**Comment by ff-dev-45** [comment]
left as future work for next team, needs some more detail to describe to next team
