### ISSUE TITLE
Setup course and enrolment schematic 

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#53]
**Describe the task that needs to be done.**
The pairing team needs a database that shows the students who are associated with a course, this will be used to perform efficient matches

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
The proposed solution will be two new tables

COURSE
courseID {primary key}(long) | courseName (String) | year/semester (string) | student count (integer) | timeUpdated (timestamp)

ENROLMENT
courseID {FK}(long) | studentID  {FK}(long) | timeCreated (timestamp)
**Notes**

**Comment by scorpionknifes** [comment]
Nit: Could we add a created timestamp or updated timestamp to courses when student count updates and enrolment is added.

This will help when debugging new enrolments/course entries.

**Comment by ff-dev-45** [comment]
I will edit now!

**Comment by ff-dev-45** [comment]
Done @scorpionknifes

**Comment by ff-dev-45** [comment]
Changed the enrolment to Course-Student, and since it uses a join table in JPA, I decided against adding the timestamp
