### ISSUE TITLE
Add auth method to get called before every endpoint

### ISSUE THREAD

**Issue by JafarMaash** [SE701-T1/backend#57]
**Describe the task that needs to be done.**
Add the auth method which will automatically get called every time before someone calls an endpoint.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Potentially use spring HandlerInterceptor to prehandle every HTTP request (see link in notes below)
This checks that the given JWT exists in the user table - could use some existing JWT library 
Take the user ID (and any other relevant info in the token) and add it as a session attribute so the endpoint method can then access it (see links in notes for example)
Remove id from UserDTO

**Notes**
This was discussed and agreed on in a Users team meeting on 14/03 - see meeting minutes in the wiki 
Aim to complete by Wednesday night :) (16/03) 

Useful links:
Handler interceptor 
https://www.baeldung.com/spring-mvc-handlerinterceptor

Example code using it 
https://github.com/eugenp/tutorials/blob/master/spring-security-modules/spring-security-web-mvc-custom/src/main/java/com/baeldung/web/interceptor/UserInterceptor.java

**Comment by scorpionknifes** [comment]
ETA?
