### ISSUE TITLE
Remove ChatObject Class from Socket Package

### ISSUE THREAD

**Issue by ejstuart** [SE701-T1/backend#63]
**Describe the task that needs to be done.**
*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*

Class was just included so that PR reviewers could make sure that the Sockets were connected. Needs to be removed.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

Deleting the class. Replacing it with our own Object Models.

**Notes**

**Comment by NicholasBatesNZ** [comment]
Fixed in #72
