### ISSUE TITLE
Changing from spring-fox to springdoc for underlying swagger-ui depdency

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#64]
**Describe the task that needs to be done.**
The current dependency used for swagger-ui is spring-fox, there is a known issue with the versions of each of these dependencies we are using[https://stackoverflow.com/questions/70178343/springfox-3-0-0-is-not-working-with-spring-boot-2-6-0](url)

This wasn't a problem up till now since we had the @EnableWebMVC annotation on our application class which seemed to hide the affect, but this shouldn't be something required to do, and it actually prevented other contexts from being used in the testing suite

currently blocking #60 

E.g unable to use @DataJpaTest for creating tests on the database, due to the servletContext being fixed by the @EnableWebMVC annotation

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Solution is to change the underlying swagger depdency from springfox to springdocs, the depdency is easily fixed with the following 
`
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.6</version>
        </dependency>
        `
Changes also need to be made to the current annotations used
These include
@Api -> @Tag(name ="name of service")
@ApiOperation -> @Operation(desc = "describe endpoint")

Finally the swagger config needs to be changed to the following
`@Configuration
public class SwaggerConfig {

    @Bean
    public OpenAPI springShopOpenAPI() {
        return new OpenAPI()
                .info(new Info().title("SpringShop API")
                        .description("Spring shop sample application")
                        .version("v0.0.1")
                        .license(new License().name("Apache 2.0").url("http://springdoc.org")))
                .externalDocs(new ExternalDocumentation()
                        .description("SpringShop Wiki Documentation")
                        .url("https://springshop.wiki.github.org/docs"));
    }
}`

**Notes**
[https://springdoc.org/#migrating-from-springfox](url)
This document helps in walking through the steps to migrate from springfox

**Comment by uoa-ppat965** [comment]
I have reviewed the issue seems like a necessary task.
