### ISSUE TITLE
Team issue labels

### ISSUE THREAD

**Issue by shreytailor** [SE701-T1/backend#65]
**Describe the task that needs to be done.**

In our meeting on 15th March, the team had proposed that we should have issue labels for each team to have more organisation. Having these labels would also make it possible to filter issues by your team, and this is great if you're looking to pick up an issue to work on.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

N/A

**Notes**

N/A

**Comment by shreyasingaraju** [comment]
LGTM!

**Comment by shreytailor** [comment]
The labels have been created!

![image](https://user-images.githubusercontent.com/39754888/158308036-77fcaa05-997e-4d39-8eef-61c756db8e4c.png)

**Comment by DanilLinkov** [comment]
LGMT
