### ISSUE TITLE
Change ical4j dependency version to 3.2.1

### ISSUE THREAD

**Issue by uoa-ypec413** [SE701-T1/backend#69]
**Describe the task that needs to be done.**
Currently the ical4j library is at version [4.0.0-alpha8](https://mvnrepository.com/artifact/org.mnode.ical4j/ical4j/4.0.0-alpha8)
This is causing an error with the `iterator()` method which prevents compilation:
![image](https://user-images.githubusercontent.com/68877945/158478043-a3e88358-89a6-41f8-bc3f-220e172808e9.png)

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Bump down ical4j dependency version from 4.0.0-alpha8 -> 3.2.1

**Notes**

**Comment by ff-dev-45** [comment]
SGTM!

**Comment by ThomasHolsterUOA** [comment]
LGTM
