### ISSUE TITLE
Population of course-student schema when a calendar is added

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#74]
**Describe the task that needs to be done.**
When a user uploads their calendar the timetable backend team created an endpoint that returns a list of strings with each string being a course name that the student is apart of.

This issue is for creating an internal method that takes in that list of strings and also the id of the student, and the method will handle the creation of any new course classes, and if the course is already present, it will ensure that the user is added to that course

This is needed to make the matching process efficient

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

A method like

`public void populateCourses(Long studentId, List<String> courses)`

This method will iterate through the list of courses and either:
1. Create a new course entity if the entity does not exist in the current database
2. If a course by the name already exists, then it will add the studentId to that course

**Notes**

**Comment by uoa-ypec413** [comment]
LGTM

**Comment by ejstuart** [comment]
LGTM, seems like a really important addition!
