### ISSUE TITLE
Thorough testing of SocketIO send/receive message events

### ISSUE THREAD

**Issue by NicholasBatesNZ** [SE701-T1/backend#80]
**Describe the task that needs to be done.**
*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*

#72 was not able to be properly tested as the front-end code was not implemented at the time of creating this issue. Make sure it works properly.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Manual testing and verification

**Notes**
Relates to #44

**Comment by scorpionknifes** [comment]
Manual testing and verification is already done with frontend when chat page is setup. Would be interesting if we could get integration testing setup in the java backend with socket io. Thoughts on refactoring the issue?

**Comment by NicholasBatesNZ** [comment]
The purpose of this issue was to ensure the current implementation works. It clearly does so I'm of the opinion that we close this off and create a new issue for integration testing.

**Comment by scorpionknifes** [comment]
Cool, make sure you
- Update the wiki (future work)
- remove this issue from Future issues to Projects
- Add issue to Future issues
