### ISSUE TITLE
Refactor user endpoints to use authorisation

### ISSUE THREAD

**Issue by uoa-ypec413** [SE701-T1/backend#82]
**Describe the task that needs to be done.**
Once the authorization interceptor is implemented, we need to refactor the user endpoints to use authorisation.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
The interceptor should handle the authorization and returning 401 Unauthorized if the user is unauthorized.
Also extract information from the token and store it for the endpoints to access.

Refactoring work will include removing the user id from the request path parameters. 
The id should instead be extracted from the interceptor somehow (depends on how issue #57 is implemented).

**Notes**
Blocked by #57

**Comment by shreytailor** [comment]
LGTM! Thanks

**Comment by JafarMaash** [comment]
LGTM :)
