### ISSUE TITLE
Adding additional user endpoints

### ISSUE THREAD

**Issue by uoa-ypec413** [SE701-T1/backend#83]
**Describe the task that needs to be done.**
Some other screens in the application require additional endpoints.

GET: /users/{id}
- Should be able to specify the user id and get back information about the user like id, email, name, buddyCount

GET: /users/
- Return information about the person who is making the request by looking at their JWT. This will also contain id, email, name, buddyCount 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Add these endpoints to UserController.

Things to consider:
- We already have the first endpoint except it returns UserDTO, the only information it is missing is buddyCount.
- Rather than buddyCount there is a list of Buddies, this should be refactored for privacy
- Do we want to expose our id (usually DTOs don't have ids, it's currently only there because we don't have auth tokens yet)?
- Do we want to get users with an id as a path parameter?
**Notes**

**Comment by shreytailor** [comment]
LGTM! Thanks

**Comment by JafarMaash** [comment]
Discussed in Users team meeting 17/03 - see wiki for minutes
