### ISSUE TITLE
Implement validate endpoint 

### ISSUE THREAD

**Issue by JafarMaash** [SE701-T1/backend#84]
**Describe the task that needs to be done.**
*(If this issue is about a bug, please describe the problem and steps to reproduce the issue. You can also include screenshots of any stack traces, or any other supporting images).*
Some pages that require auth might not make requests to the backend, so there's no real way to find out whether the user concerned is authenticated or not. so we need a quick way to find out if their JWT is valid b hitting an endpoint. 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Create an endpoint like /api/validate (in a new validateController) to verify a JWT passed in from the front end. This will call the validateToken() method in the JWTUtil class, and return the result 
**Notes**
Created in Users team meeting 17/03 (see wiki for minutes)

**Comment by shreytailor** [comment]
LGTM! Thanks
