### ISSUE TITLE
User repository method name change is breaking tests

### ISSUE THREAD

**Issue by ff-dev-45** [SE701-T1/backend#85]
**Describe the task that needs to be done.**
Through the process of refactoring `retrieve` to `retrieveById` a few tests in other services now fail, and this needs to ideally be fixed.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
update all usages of `retrieve` -> `retrieveById` and the tests will pass fine

Will also create another issue to bump automated tests which would have helped avoid this problem

**Notes**

**Comment by JafarMaash** [comment]
LGTM
